### ISSUE TITLE
Liger-Kernel crashes on very long seqlen 2^31 / int64 indexing issue

### ISSUE THREAD

**Issue by sfc-gh-sbekman** [linkedin/Liger-Kernel#803]
### 🐛 Describe the bug

Hi, in the context of developing support for training with very long seqlen https://www.arxiv.org/abs/2506.13996 - we are trying to break past 500K seqlen on a single gpu - that limit was fine on H100 with 80GB, but with H200 and B200 we have a lot more memory available and should be able to do more than 1M seqlen easily - but I'm running into int64 indexing issue with Liger-Kernel (and FA2 as well, but FA3 solves it).

Liger's rms norm crashes with:

```
[rank0]: RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

Please note that already at 500K and 8B llama we are dealing with `[1, 500_000, 4096]` a tensor of about 2^31 - which is the cause of the problem.

### Reproduce

```
import torch
import gc
from liger_kernel.transformers import AutoLigerKernelForCausalLM

checkpoint = "meta-llama/Llama-3.1-8B-Instruct"

torch.manual_seed(42)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
dtype=torch.bfloat16

model = AutoLigerKernelForCausalLM.from_pretrained(checkpoint, torch_dtype=dtype).to(device)

seqlen = 1_000_000
hidden_size = model.config.hidden_size
hidden_states = torch.rand((1, seqlen, hidden_size), dtype=torch.bfloat16, requires_grad=True, device=device)

for idx in range(len(model.model.layers)):
    hidden_states = model.model.layers[idx].input_layernorm(hidden_states)
    print(f"{idx} {hidden_states.shape=}")
    gc.collect()
```

gives us:
```
0 hidden_states.shape=torch.Size([1, 1000000, 4096])
1 hidden_states.shape=torch.Size([1, 1000000, 4096])
Traceback (most recent call last):
  File "/code/users/stas/github/sf/arctictraining/long-seqlen-fa-liger.py", line 24, in <module>
    hidden_states = model.model.layers[idx].input_layernorm(hidden_states)
  File "/home/yak/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yak/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yak/.local/lib/python3.10/site-packages/liger_kernel/transformers/rms_norm.py", line 33, in forward
    return LigerRMSNormFunction.apply(
  File "/home/yak/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/yak/.local/lib/python3.10/site-packages/liger_kernel/ops/utils.py", line 40, in wrapper
    return fn(ctx, *args, **kwargs)
  File "/home/yak/.local/lib/python3.10/site-packages/liger_kernel/ops/rms_norm.py", line 556, in forward
    Y, X, RSTD, BLOCK_SIZE, num_warps, casting_mode = rms_norm_forward(X, W, eps, offset, casting_mode, row_mode)
  File "/home/yak/.local/lib/python3.10/site-packages/liger_kernel/ops/rms_norm.py", line 400, in rms_norm_forward
    _rms_norm_forward_kernel[(n_rows,)](
  File "/home/yak/.local/lib/python3.10/site-packages/triton/runtime/jit.py", line 347, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/yak/.local/lib/python3.10/site-packages/triton/runtime/jit.py", line 591, in run
    kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata,
  File "/home/yak/.local/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 529, in __call__
    self.launch(gridX, gridY, gridZ, stream, function, self.launch_cooperative_grid, global_scratch, *args)
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

### Versions

```
Operating System: Linux-5.10.235-227.919.amzn2.x86_64-x86_64-with-glibc2.35
Python version: 3.10.12
Liger Kernel version: 0.6.0
PyTorch version: 2.7.1+cu128
CUDA version: 12.8
HIP(ROCm) version: Not available
Triton version: 3.3.1
Transformers version: 4.54.0.dev0
XPU version: XPU Not Available
```

**Comment by vvvdwbvvv** [comment]
repro with
```
  import torch
  import gc
  from liger_kernel.ops.rms_norm import LigerRMSNormFunction
  
  # export CUDA_LAUNCH_BLOCKING=1
  # export TORCH_USE_CUDA_DSA=1
  
  torch.manual_seed(42)
  device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
  dtype=torch.bfloat16
  
  seqlen = 1_000_000
  for hidden_size in [512, 1024, 2048, 4096, 8192]:
      X = torch.rand((1, seqlen, hidden_size),
                  dtype=dtype,
                  device=device)
      torch.cuda.synchronize()
      print(f"  → Allocated X with shape={X.shape}, numel={X.numel()}")
  
      W = torch.ones((hidden_size,), dtype=dtype, device=device)
      torch.cuda.synchronize()
  
      try:
          Y = LigerRMSNormFunction.apply(X, W, 1e-5, False, 0, False)
          torch.cuda.synchronize()
          print(f"{hidden_size}: OK")
      except RuntimeError as e:
          print(f"{hidden_size}: ERROR@LayerNorm → {e}")
      
      gc.collect()
      torch.cuda.empty_cache()
```
Got :
```
(venv) (workenv) root@eg632kg3:~/tmp# python test.py 
  → Allocated X with shape=torch.Size([1, 1000000, 512]), numel=512000000
512: OK
  → Allocated X with shape=torch.Size([1, 1000000, 1024]), numel=1024000000
1024: OK
  → Allocated X with shape=torch.Size([1, 1000000, 2048]), numel=2048000000
2048: OK
  → Allocated X with shape=torch.Size([1, 1000000, 4096]), numel=4096000000
4096: ERROR@LayerNorm → Triton Error [CUDA]: an illegal memory access was encountered
Traceback (most recent call last):
  File "/root/tmp/test.py", line 14, in <module>
    X = torch.rand((1, seqlen, hidden_size),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by vvvdwbvvv** [comment]
@sfc-gh-sbekman @Tcc0403 Fixed in #804

**Comment by winglian** [comment]
@vvvdwbvvv the stack trace only shows LigerRMSNorm, but likely other kernels are affected too?

**Comment by vvvdwbvvv** [comment]
Thank you for the reminding,I would work on some test on both forward and backward

**Comment by sfc-gh-sbekman** [comment]
Thank you so much for working on this, @vvvdwbvvv - It's not yet fixed - let's continue the discussion in the PR you created.
